<?xml version="1.0" encoding="utf-8" ?>
<!-- <?php exit(); ?> -->
<scabbia>
    <info>
        <name>views</name>
        <version>1.1.0</version>
        <license>GPLv3</license>
        <phpversion>5.3.0</phpversion>
        <phpdependList />
        <fwversion>1.1</fwversion>
        <fwdependList>
            <fwdepend>string</fwdepend>
            <fwdepend>http</fwdepend>
            <fwdepend>resources</fwdepend>
            <fwdepend>cache</fwdepend>
        </fwdependList>
    </info>
    <eventList>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\Views::extensionLoad</value>
        </event>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\ViewEngineMarkdown::extensionLoad</value>
        </event>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\ViewEnginePhptal::extensionLoad</value>
        </event>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\ViewEngineRaintpl::extensionLoad</value>
        </event>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\ViewEngineRazor::extensionLoad</value>
        </event>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\ViewEngineSmarty::extensionLoad</value>
        </event>
        <event>
            <name>load</name>
            <type>callback</type>
            <value>Scabbia\Extensions\Views\ViewEngineTwig::extensionLoad</value>
        </event>
    </eventList>
</scabbia>