<?xml version="1.0" encoding="utf-8" ?>
<!-- <?php exit(); ?> -->
<scabbia>
	<info>
		<name>views</name>
		<version>1.1.0</version>
		<license>GPLv3</license>
		<phpversion>5.3.0</phpversion>
		<phpdependList />
		<fwversion>1.1</fwversion>
		<fwdependList>
			<fwdepend>string</fwdepend>
			<fwdepend>http</fwdepend>
			<fwdepend>resources</fwdepend>
			<fwdepend>cache</fwdepend>
		</fwdependList>
	</info>
	<eventList>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\views::extensionLoad</callback>
		</event>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\viewEngineMarkdown::extensionLoad</callback>
		</event>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\viewEnginePhptal::extensionLoad</callback>
		</event>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\viewEngineRaintpl::extensionLoad</callback>
		</event>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\viewEngineRazor::extensionLoad</callback>
		</event>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\viewEngineSmarty::extensionLoad</callback>
		</event>
		<event>
			<name>load</name>
			<callback>Scabbia\Extensions\Views\viewEngineTwig::extensionLoad</callback>
		</event>
	</eventList>
</scabbia>