<?xml version="1.0" encoding="utf-8" ?>
<!-- <?php exit(); ?> -->
<scabbia>
	<http>
		<link>{@siteroot}/{@path}</link>

<!--
		<rewriteList>
			<rewrite>
				<limitMethods>
					<get />
				</limitMethods>
				<match>regions/([a-z_]+)/([a-z_]+)/([a-z0-9\-]+)</match>
				<forward>firms/$3</forward>
			</rewrite>
		</rewriteList>
-->

		<routeList>
			<route>
				<match><![CDATA[(controller:alnum)?/?(action:alnum)?(params:/+[^?&]*)?(query:[?&].*)?]]></match>
				<callback>Scabbia\Extensions\Mvc\mvc::route</callback>
			</route>
		</routeList>

		<errorPages>
			<notfound>shared/error.php</notfound>
			<restriction>shared/error.php</restriction>
			<maintenance>shared/error.php</maintenance>
			<ipban>shared/error.php</ipban>
			<error>shared/error.php</error>
		</errorPages>

		<userAgents>
			<autoCheck>0</autoCheck>
			<platformList>
				<platform>
					<match>windows|winnt|win95|win98</match>
					<name>Windows</name>
				</platform>
				<platform>
					<match>os x|ppc mac|ppc</match>
					<name>MacOS</name>
				</platform>
				<platform>
					<match>irix|netbsd|freebsd|openbsd|bsdi|unix|sunos|linux|debian|gnu</match>
					<name>Unix</name>
				</platform>
			</platformList>

			<crawlerList>
				<crawler>
					<type>bot</type>
					<match>googlebot|msnbot|slurp|yahoo|askjeeves|fastcrawler|infoseek|lycos</match>
					<name>Searchbot</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Opera</match>
					<name>Opera</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Mozilla|Firefox|Firebird|Phoenix</match>
					<name>Firefox</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>MSIE|Internet Explorer</match>
					<name>Internet Explorer</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Flock</match>
					<name>Flock</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Chrome</match>
					<name>Chrome</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Shiira</match>
					<name>Shiira</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Chimera</match>
					<name>Chimera</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Camino</match>
					<name>Camino</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Netscape</match>
					<name>Netscape</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>OmniWeb</match>
					<name>OmniWeb</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Safari</match>
					<name>Safari</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Konqueror</match>
					<name>Konqueror</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>icab</match>
					<name>iCab</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Lynx</match>
					<name>Lynx</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>Links</match>
					<name>Links</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>hotjava</match>
					<name>HotJava</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>amaya</match>
					<name>Amaya</name>
				</crawler>
				<crawler>
					<type>browser</type>
					<match>IBrowse</match>
					<name>IBrowse</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>palm|elaine</match>
					<name>Palm</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>iphone|ipod</match>
					<name>iOS</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>blackberry</match>
					<name>Blackberry</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>symbian|series60</match>
					<name>SymbianOS</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>windows ce</match>
					<name>Windows CE</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>opera mini|operamini</match>
					<name>Opera Mini</name>
				</crawler>
				<crawler>
					<type>mobile</type>
					<match>mobile|wireless|j2me|phone</match>
					<name>Other Mobile</name>
				</crawler>
			</crawlerList>
		</userAgents>
	</http>

<!--
	<session>
		<cookie>
			<name>sessid</name>
			<life>0</life>
			<ipCheck>0</ipCheck>
			<uaCheck>1</uaCheck>
		</cookie>
	</session>

	<access>
		<maintenance>
			<mode>0</mode>
			<page>{app}views/static_maintenance.php</page>
			<mvcpage>shared/maintenance.cshtml</mvcpage>
			<ipExcludeList>
				<ipExclude>127.0.0.1</ipExclude>
			</ipExcludeList>
		</maintenance>

		<ipFilter>
			<page>{app}views/static_ipban.php</page>
			<mvcpage>shared/ipban.cshtml</mvcpage>
			<ipFilterList>
				<ipFilter>
					<type>deny</type>
					<pattern>188.0.0.?</pattern>
				</ipFilter>
				<ipFilter>
					<type>allow</type>
					<pattern>*.*.*.*</pattern>
				</ipFilter>
			</ipFilterList>
		</ipFilter>
	</access>
-->
</scabbia>