<?php

if(Extensions::isSelected('logger')) {
	class logger {
		public static $filename;
		public static $line;
		public static $eof = "\r\n";
		public static $directory;

		public static function extension_info() {
			return array(
				'name' => 'logger',
				'version' => '1.0.2',
				'phpversion' => '5.1.0',
				'phpdepends' => array(),
				'fwversion' => '1.0',
				'fwdepends' => array('string', 'http')
			);
		}

		public static function extension_load() {
			self::$filename = Config::get('/logger/@filename', '{date|\'d-m-Y\'}.txt');
			self::$line = Config::get('/logger/@line', '[{date|\'d-m-Y H:i:s\'}] {strtoupper|@category} | {@ip} | {@message}');
			
			self::$directory = QPATH_APP . 'writable/logs/';

			set_exception_handler('logger::exceptionCallback');
			set_error_handler('logger::errorCallback', E_ALL);
			// ini_set('display_errors', '1');
			// ini_set('track_errors', '1');
			// ini_set('html_errors', '0');
		}

		public static function errorCallback($uCode, $uMessage, $uFile, $uLine) {
			throw new ErrorException($uMessage, $uCode, 0, $uFile, $uLine);
		}

		public static function exceptionCallback($uException) {
			switch($uException->getCode()) {
				case E_ERROR:
				case E_USER_ERROR:
				case E_RECOVERABLE_ERROR:
					$tType = 'Error';
					break;
				case E_WARNING:
				case E_USER_WARNING:
					$tType = 'Warning';
					break;
				case E_NOTICE:
				case E_USER_NOTICE:
					$tType = 'Notice';
					break;
				case E_STRICT:
					$tType = 'Strict';
					break;
				// case E_DEPRECATED: // PHP >= 5.3.0
				case 8192:
				// case E_USER_DEPRECATED: // PHP >= 5.3.0
				case 16384:
					break;
				default:
					$tType = 'Unknown';
					break;
			}

			$tIgnoreError = false;
			Events::invoke('reportError', array(
				'type' => &$tType,
				'message' => $uException->getMessage(),
				'file' => $uException->getFile(),
				'line' => $uException->getLine(),
				'ignore' => &$tIgnoreError
			));

			if(!$tIgnoreError) {
				http::sendStatus(500);
				http::sendHeader('Content-Type', 'text/html', true);

				Events::setDisabled(true);
				$tEventDepth = Events::getEventDepth();

				for($tCount = ob_get_level(); --$tCount > 1;ob_end_flush());

				if(Framework::$development) {
					$tDeveloperLocation = pathinfo($uException->getFile(), PATHINFO_FILENAME) . ' @' . $uException->getLine();
				}
				else {
					$tDeveloperLocation = '';
				}

				$tString = '';
				$tString .= '<div>'; // for content-type: text/xml
				$tString .= '<div style="font: 11pt \'Lucida Sans Unicode\'; color: #000060; border-bottom: 1px solid #C0C0C0; background: #F0F0F0; padding: 8px 12px 8px 12px;"><span style="font-weight: bold;">' . $tType . '</span>: ' . $tDeveloperLocation . '</div>' . self::$eof;
				$tString .= '<div style="font: 10pt \'Lucida Sans Unicode\'; color: #404040; padding: 0px 12px 0px 12px; margin: 20px 0px 20px 0px; line-height: 20px;">' . $uException->getMessage() . '</div>' . self::$eof;

				if(Framework::$development) {
					if(count($tEventDepth) > 0) {
						$tString .= '<div style="font: 10pt \'Lucida Sans Unicode\'; color: #800000; padding: 0px 12px 0px 12px; margin: 20px 0px 20px 0px; line-height: 20px;"><b>eventDepth:</b>' . implode('<br />' . self::$eof, $tEventDepth) . '</div>' . self::$eof;
					}
					
					$tString .= '<div style="font: 10pt \'Lucida Sans Unicode\'; color: #800000; padding: 0px 12px 0px 12px; margin: 20px 0px 20px 0px; line-height: 20px;"><b>stackTrace:</b>' . $uException->getTraceAsString() . '</div>' . self::$eof;
				}

				$tString .= '</div>';

				self::write('error', array('message' => $uException->__toString()));

				$tString .= '<div style="font: 7pt \'Lucida Sans Unicode\'; color: #808080; padding: 0px 12px 0px 12px;">Generated by <a href="mailto:eser@sent.com">' . ucfirst(INCLUDED) . '</a>.</div>';
				echo $tString;

				exit();
			}
		}

		public static function write($uCategory, $uParams) {
			$uParams['category'] = &$uCategory;
			$uParams['ip'] = $_SERVER['REMOTE_ADDR'];

			$tFilename = self::$directory . string::format(self::$filename, $uParams);
			$tContent = string::format(self::$line . self::$eof . self::$eof, $uParams);

			file_put_contents($tFilename, $tContent, FILE_APPEND);
		}
	}
}

?>