<?xml version="1.0" encoding="utf-8" ?>
<!-- <?php exit(); ?> -->
<scabbia>
    <captcha>
        <fontFile>{vendor}resources/fonts/KabobExtrabold.ttf</fontFile>
    </captcha>

    <resources>
        <directoryList>
            <directory>
                <name>scabbia/</name>
                <path>{vendor}resources/</path>
            </directory>
            <scope mode="development">
                <directory>
                    <name>docs/</name>
                    <path>{vendor}resources/docs/</path>
                    <autoViewer>
                        <defaultPage>index.md</defaultPage>
                        <viewEngine>viewEngineMarkdown</viewEngine>
                        <header>{vendor}views/docs/header.php</header>
                        <footer>{vendor}views/docs/footer.php</footer>
                    </autoViewer>
                </directory>
            </scope>
        </directoryList>
        <fileList />
        <packList>
            <pack>
                <name>scabbia.js</name>
                <type>js</type>
                <cacheTtl>86400</cacheTtl>
                <partList>
                    <part>
                        <type>file</type>
                        <class>core</class>
                        <path>{vendor}resources/laroux/laroux.js</path>
                    </part>
                    <part>
                        <type>function</type>
                        <class>core</class>
                        <name>Scabbia\Extensions\Mvc\mvc::exportAjaxJs</name>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jquery</class>
                        <path>{vendor}resources/jquery/sizzle.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jquery</class>
                        <path>{vendor}resources/jquery/jquery-1.8.1-custom.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jquery</class>
                        <path>{vendor}resources/jquery/jquery.fix.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.core.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.widget.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.mouse.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.position.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.sortable.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.tabs.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.autocomplete.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.datepicker.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/laroux/laroux.ui.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryuifx</class>
                        <path>{vendor}resources/jquery/jquery.effects.core.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryuifx</class>
                        <path>{vendor}resources/jquery/jquery.effects.highlight.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryuifx</class>
                        <path>{vendor}resources/jquery/jquery.effects.shake.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>validation</class>
                        <path>{vendor}resources/jquery/jquery.validate.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>validation</class>
                        <path>{vendor}resources/jquery/jquery.validate.additional-methods.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>map</class>
                        <path>{vendor}resources/mapbox/mapbox-0.6.5.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>cleditor</class>
                        <path>{vendor}resources/cleditor/jquery.cleditor.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>cleditor</class>
                        <path>{vendor}resources/cleditor/jquery.cleditor.xhtml.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>shadowbox</class>
                        <path>{vendor}resources/shadowbox/shadowbox.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>tablesorter</class>
                        <path>{vendor}resources/tablesorter/jquery.tablesorter.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>tablesorter</class>
                        <path>{vendor}resources/tablesorter/jquery.tablesorter.pager.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>snippet</class>
                        <path>{vendor}resources/snippet/jquery.snippet.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>flot</class>
                        <path>{vendor}resources/flot/jquery.flot.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>flot</class>
                        <path>{vendor}resources/flot/jquery.flot.pie.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>tipsy</class>
                        <path>{vendor}resources/tipsy/jquery.tipsy.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>maskedinput</class>
                        <path>{vendor}resources/maskedinput/jquery.maskedinput-1.3.js</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>blackmore</class>
                        <path>{vendor}resources/blackmore/blackmore.js</path>
                    </part>
                </partList>
            </pack>
            <pack>
                <name>scabbia.css</name>
                <type>css</type>
                <cacheTtl>86400</cacheTtl>
                <partList>
                    <part>
                        <type>file</type>
                        <class>reset</class>
                        <path>{vendor}resources/reset/reset.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>errorpages</class>
                        <path>{vendor}resources/errorpages/errorpages.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.core.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.autocomplete.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.tabs.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.datepicker.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/jquery/jquery.ui.theme.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>jqueryui</class>
                        <path>{vendor}resources/laroux/laroux.ui.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>map</class>
                        <path>{vendor}resources/mapbox/mapbox.0.6.5.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>cleditor</class>
                        <path>{vendor}resources/cleditor/jquery.cleditor.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>shadowbox</class>
                        <path>{vendor}resources/shadowbox/shadowbox.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>tablesorter</class>
                        <path>{vendor}resources/tablesorter/style.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>snippet</class>
                        <path>{vendor}resources/snippet/jquery.snippet.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>tipsy</class>
                        <path>{vendor}resources/tipsy/tipsy.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>blackmore</class>
                        <path>{vendor}resources/blackmore/blackmore.css</path>
                    </part>
                    <part>
                        <type>file</type>
                        <class>docs</class>
                        <path>{vendor}resources/docs/markdown.css</path>
                    </part>
                </partList>
            </pack>
        </packList>
    </resources>
</scabbia>